### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by C0rn3j** [kirei/python-base45#1]
How would I go about using this tool from the shell?

```python
python --version                                                                                                                 
Python 3.9.5

echo -e 'alfa' | ./base45 --encode
Traceback (most recent call last):
  File "/home/c0rn3j/.local/bin/./base45", line 8, in <module>
    sys.exit(main())
  File "/home/c0rn3j/.local/lib/python3.9/site-packages/base45/cli.py", line 25, in main
    sys.stdout.write(b45encode(data))
TypeError: write() argument must be str, not bytes
```
```python
cat cert | ./base45 --decode
Traceback (most recent call last):
  File "/home/c0rn3j/.local/lib/python3.9/site-packages/base45/__init__.py", line 32, in b45decode
    buf = [BASE45_CHARSET.index(c) for c in s]
  File "/home/c0rn3j/.local/lib/python3.9/site-packages/base45/__init__.py", line 32, in <listcomp>
    buf = [BASE45_CHARSET.index(c) for c in s]
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/c0rn3j/.local/bin/./base45", line 8, in <module>
    sys.exit(main())
  File "/home/c0rn3j/.local/lib/python3.9/site-packages/base45/cli.py", line 28, in main
    sys.stdout.buffer.write(b45decode(data.decode()))
  File "/home/c0rn3j/.local/lib/python3.9/site-packages/base45/__init__.py", line 45, in b45decode
    raise ValueError("Invalid base45 string")
ValueError: Invalid base45 string
```

cert contents
```
HC1:NCFOXN%TS3DH3ZSUZK+.V0ETD%65NL-AH-R6IOO6+IUKRG*I.I5BROCWAAT4V22F/8X*G3M9JUPY0BX/KR96R/S09T./0LWTKD33236J3TA3M*4VV2 73-E3GG396B-43O058YIB73A*G3W19UEBY5:PI0EGSP4*2DN43U*0CEBQ/GXQFY73CIBC:G 7376BXBJBAJ UNFMJCRN0H3PQN*E33H3OA70M3FMJIJN523.K5QZ4A+2XEN QT QTHC31M3+E32R44$28A9H0D3ZCL4JMYAZ+S-A5$XKX6T2YC 35H/ITX8GL2-LH/CJTK96L6SR9MU9RFGJA6Q3QR$P2OIC0JVLA8J3ET3:H3A+2+33U SAAUOT3TPTO4UBZIC0JKQTL*QDKBO.AI9BVYTOCFOPS4IJCOT0$89NT2V457U8+9W2KQ-7LF9-DF07U$B97JJ1D7WKP/HLIJLRKF1MFHJP7NVDEBU1J*Z222E.GJF67Z JA6B.38O4BH*HB0EGLE2%V -3O+J3.PI2G:M1SSP2Y3D38-G9C+Q3OT/.J1CDLKOYUV5C3W1A:75S4LB:6REPKM3ZYO4+QDNDLT2*ESLIH
```

**Comment by jschlyter** [comment]
Fixed in 4f19df4a4434c4fdb138142bb5d84a7029623bdb.

This now works: `echo "foo" | base45 --encode | base45 --decode`

**Comment by jschlyter** [comment]
Please keep in mind that it is only the data after `HC1:` that is base45 encoded, not the `HC1:` preamble.

**Comment by C0rn3j** [comment]
Thanks!
There's still a small issue - the tool can't handle dealing with a final newline in a file

```bash
echo "foo" | ./base45 --encode > /tmp/test && echo >> /tmp/test && cat /tmp/test |  ./base45 --decode
```

**Comment by jschlyter** [comment]
Ah, I've fixed so it will strip the string before parsing. The CLI is just a tool, if one want more features direct library use is recommended.
