### ISSUE TITLE
can't decode a eudgc base45 encoded string

### ISSUE THREAD

**Issue by zeph** [kirei/python-base45#4]
hi, I apologize if this is not the right place... but since I'm attempting to use this library (version `0.2.1`) to decode a base45 string... I really would need to figure out if I'm not testing with a malformed string... or if it is a library problem... 

`"6BFOXN%TS3DH0YOJ58S S-W5HDC *M0II5XHC9B5G2+$N IOP-IA%NFQGRJPC%OQHIZC4.OI1RM8ZA.A5:S9MKN4NN3F85QNCY0O%0VZ001HOC9JU0D0HT0HB2PL/IB*09B9LW4T*8+DCMH0LDK2%K:XFE70*LP$V25$0Q:J:4MO1P0%0L0HD+9E/HY+4J6TH48S%4K.GJ2PT3QY:GQ3TE2I+-CPHN6D7LLK*2HG%89UV-0LZ 2ZJJ524-LH/CJTK96L6SR9MU9DHGZ%P WUQRENS431T1XCNCF+47AY0-IFO0500TGPN8F5G.41Q2E4T8ALW.INSV$ 07UV5SR+BNQHNML7 /KD3TU 4V*CAT3ZGLQMI/XI%ZJNSBBXK2:UG%UJMI:TU+MMPZ5$/PMX19UE:-PSR3/$NU44CBE6DQ3D7B0FBOFX0DV2DGMB$YPF62I$60/F$Z2I6IFX21XNI-LM%3/DF/U6Z9FEOJVRLVW6K$UG+BKK57:1+D10%4K83F+1VWD1NE"` seems to get me a 

```  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 32, in b45decode
    buf = [BASE45_CHARSET.index(c) for c in s]
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 32, in <listcomp>
    buf = [BASE45_CHARSET.index(c) for c in s]
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/bin/base45", line 8, in <module>
    sys.exit(main())
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/cli.py", line 28, in main
    sys.stdout.buffer.write(b45decode(data.decode()))
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 45, in b45decode
    raise ValueError("Invalid base45 string")
ValueError: Invalid base45 string
```

I initially opened the ticket on this other project... https://github.com/siddolo/eHealthDecoder/issues/2

**Comment by jschlyter** [comment]
Please try with version the latest version (v0.3.1). Just tried and it works here.

**Comment by zeph** [comment]
I did... with `0.3.1` too but...
```$ pip list
Package           Version
----------------- --------
asn1crypto        1.4.0
attrs             21.2.0
base45            0.3.1
cbor2             5.4.0
certvalidator     0.11.1
cffi              1.14.5
cose              0.9.dev7
cryptography      3.4.7
cv2-tools         2.4.0
ecdsa             0.17.0
ImageHash         4.2.0
numpy             1.20.3
opencv-python     4.5.2.54
oscrypto          1.2.1
Pillow            8.2.0
pip               21.0.1
pycparser         2.20
python-constraint 1.4.0
PyWavelets        1.1.1
pyzbar            0.1.8
qrcode            6.1
scipy             1.6.3
setuptools        54.0.0
six               1.16.0
wheel             0.36.2
WARNING: You are using pip version 21.0.1; however, version 21.1.3 is available.
You should consider upgrading via the '/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/bin/python -m pip install --upgrade pip' command.
```
```
$ curl https://raw.githubusercontent.com/eu-digital-green-certificates/dgc-testdata/main/IT/2DCode/raw/1.json|jq .BASE45|base45 --decode
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8093  100  8093    0     0  20137      0 --:--:-- --:--:-- --:--:-- 20182
Traceback (most recent call last):
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 32, in b45decode
    buf = [BASE45_CHARSET.index(c) for c in s.strip()]
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 32, in <listcomp>
    buf = [BASE45_CHARSET.index(c) for c in s.strip()]
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/bin/base45", line 8, in <module>
    sys.exit(main())
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/cli.py", line 28, in main
    sys.stdout.buffer.write(b45decode(data.decode()))
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 47, in b45decode
    raise ValueError("Invalid base45 string")
ValueError: Invalid base45 string
```
or more explicitly

```
$ echo "6BFOXN%TS3DH0YOJ58S S-W5HDC *M0II5XHC9B5G2+$N IOP-IA%NFQGRJPC%OQHIZC4.OI1RM8ZA.A5:S9MKN4NN3F85QNCY0O%0VZ001HOC9JU0D0HT0HB2PL/IB*09B9LW4T*8+DCMH0LDK2%K:XFE70*LP$V25$0Q:J:4MO1P0%0L0HD+9E/HY+4J6TH48S%4K.GJ2PT3QY:GQ3TE2I+-CPHN6D7LLK*2HG%89UV-0LZ 2ZJJ524-LH/CJTK96L6SR9MU9DHGZ%P WUQRENS431T1XCNCF+47AY0-IFO0500TGPN8F5G.41Q2E4T8ALW.INSV$ 07UV5SR+BNQHNML7 /KD3TU 4V*CAT3ZGLQMI/XI%ZJNSBBXK2:UG%UJMI:TU+MMPZ5$/PMX19UE:-PSR3/$NU44CBE6DQ3D7B0FBOFX0DV2DGMB$YPF62I$60/F$Z2I6IFX21XNI-LM%3/DF/U6Z9FEOJVRLVW6K$UG+BKK57:1+D10%4K83F+1VWD1NE"|base45 --decode
Traceback (most recent call last):
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 32, in b45decode
    buf = [BASE45_CHARSET.index(c) for c in s.strip()]
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 32, in <listcomp>
    buf = [BASE45_CHARSET.index(c) for c in s.strip()]
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/bin/base45", line 8, in <module>
    sys.exit(main())
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/cli.py", line 28, in main
    sys.stdout.buffer.write(b45decode(data.decode()))
  File "/home/gms/tmp/local/qr_encode_disaster_recovery/.p3/lib/python3.9/site-packages/base45/__init__.py", line 47, in b45decode
    raise ValueError("Invalid base45 string")
ValueError: Invalid base45 string
```
I can try installing just that... a sec

**Comment by zeph** [comment]
nope...

```
$ virtualenv .p3
created virtual environment CPython3.9.5.final.0-64 in 845ms
  creator CPython3Posix(dest=/home/gms/tmp/local/eHealthDecoder/.p3, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/gms/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
```

`$ source .p3/bin/activate`

```
$ pip install base45
Collecting base45
  Using cached base45-0.3.1-py3-none-any.whl (3.4 kB)
Installing collected packages: base45
Successfully installed base45-0.3.1
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the '/home/gms/tmp/local/eHealthDecoder/.p3/bin/python -m pip install --upgrade pip' command.
```
`$ echo "6BFOXN%TS3DH0YOJ58S S-W5HDC *M0II5XHC9B5G2+$N IOP-IA%NFQGRJPC%OQHIZC4.OI1RM8ZA.A5:S9MKN4NN3F85QNCY0O%0VZ001HOC9JU0D0HT0HB2PL/IB*09B9LW4T*8+DCMH0LDK2%K:XFE70*LP$V25$0Q:J:4MO1P0%0L0HD+9E/HY+4J6TH48S%4K.GJ2PT3QY:GQ3TE2I+-CPHN6D7LLK*2HG%89UV-0LZ 2ZJJ524-LH/CJTK96L6SR9MU9DHGZ%P WUQRENS431T1XCNCF+47AY0-IFO0500TGPN8F5G.41Q2E4T8ALW.INSV$ 07UV5SR+BNQHNML7 /KD3TU 4V*CAT3ZGLQMI/XI%ZJNSBBXK2:UG%UJMI:TU+MMPZ5$/PMX19UE:-PSR3/$NU44CBE6DQ3D7B0FBOFX0DV2DGMB$YPF62I$60/F$Z2I6IFX21XNI-LM%3/DF/U6Z9FEOJVRLVW6K$UG+BKK57:1+D10%4K83F+1VWD1NE"|base45 --decode`
```
Traceback (most recent call last):
  File "/home/gms/tmp/local/eHealthDecoder/.p3/lib/python3.9/site-packages/base45/__init__.py", line 32, in b45decode
    buf = [BASE45_CHARSET.index(c) for c in s.strip()]
  File "/home/gms/tmp/local/eHealthDecoder/.p3/lib/python3.9/site-packages/base45/__init__.py", line 32, in <listcomp>
    buf = [BASE45_CHARSET.index(c) for c in s.strip()]
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gms/tmp/local/eHealthDecoder/.p3/bin/base45", line 8, in <module>
    sys.exit(main())
  File "/home/gms/tmp/local/eHealthDecoder/.p3/lib/python3.9/site-packages/base45/cli.py", line 28, in main
    sys.stdout.buffer.write(b45decode(data.decode()))
  File "/home/gms/tmp/local/eHealthDecoder/.p3/lib/python3.9/site-packages/base45/__init__.py", line 47, in b45decode
    raise ValueError("Invalid base45 string")
ValueError: Invalid base45 string
```

**Comment by jschlyter** [comment]
It seems your `echo` is not properly escaped, so the input to `base45 --decode` is not what you think it is.

**Comment by bitsec12** [comment]
When I run

`echo "$T9ZKE ZDZC9$QE ZD+EDR44YEDP9E3EFMVCN$D3EF7WEBAFN44:+CAWEDZCV9EZEDBWE3/D9440/DS44%FF6$C7$CBWE3/DH440/D7%EKWEHEFX3404E0$CU34W9E1%EG44HECA44$ CM-DAWEDZCZEDMVC QEALEJ:4R443WE0/DGECRTCMVCN$D3EF7WEBAFD44O/EBJEPQE:.DDZCAWEDZC.966469PEV44+8DM-DCECT447/DB/DJ4FO44*KEG/D5$CS44.3EJODOCC53D VDC$CN44:+CRWEI9E9440/DR44XPCBEC-JC  CH44SUEHWEL449ECDZCOCCRWEI9ER44I9EOPCF$DM-D:JC%3EI$5*C9G44HECR446%ES/EO/ERTCB/DSUE-3E4WDE44/EDDZCKPCG/D6%EQED9PEA448%E944/VD82EAWEDZCTVDEECH44G/D82E: CZ CKWE-3EOEDS44%FF6$C7$CBWE3/D1Q5ZKEB$DZEDZEDU1D6$CLQEG/DMED VD3EF2%ENPCCEC93D-TCU34SUE64F.OES9EY9EPVD*KELQERTCZEDS44+8D634LA7S56V44-EDG7DAWEDZCZKETVDHECDZCX3EX347$CVKELQESUEOQE$ CLWEB44-3E3WEZEDZEDU1D$T9ZKE ZDZC9$QE ZDE9EZQE5EC6$C1Q5CECRTCP$DZKEQ44Z C1$CEWE3EFE4FAWEC446$CDQD/3EO44Z$EXVDOQEZEDU1DVQE%.C64FZKEK44WEDDZC8C8MVC.OEC7A93D9Z9/PDBJEZEDRPC$$EZEDU1DO/E4LE EDF/DN44:+C$T9ZKE ZDZC9$QE5 DA0" |base45 --decode `

I get the same @zeph error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/base45/__init__.py", line 41, in b45decode
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/base45", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/base45/cli.py", line 28, in main
    sys.stdout.buffer.write(b45decode(data.decode()))
  File "/usr/local/lib/python3.9/site-packages/base45/__init__.py", line 47, in b45decode
    raise ValueError("Invalid base45 string")
ValueError: Invalid base45 string
```

**Comment by jschlyter** [comment]
Just as with @zeph, @bitsec12 you are not escaping your input properly - your shell will try to expand the `$`. Put the data in a fil and use `base45 --decode < file` and see if that works.

**Comment by eriol** [comment]
@zeph try this:
```
curl -sS https://raw.githubusercontent.com/eu-digital-green-certificates/dgc-testdata/main/IT/2DCode/raw/1.json | jq -r .BASE45 | base45 --decode
```

it works for me using base45 0.3.1. Please note that I used `jq -r .BASE45` to get the raw string, otherwise the string you get will have double quotes at the beginning and at the end, and `"` is not inside base45 charset.

**Comment by zeph** [comment]
yup, that works! tnx
